### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by thesues** [bd-iaas-us/infiniStore#1]
- [x] Async kvcache Python API and benchmark
- [x] RDMA+GDR support and benchmark
- [x] Simple Proxy or scheduler (two nodes backend) PoC

After milestone1, we could submit a RFC to VLLM upstream

**Comment by thesues** [comment]
-[ ] support batch read/write
-[ ] valgrind test memory leak
-[ ] unit test and CI
-[ ] rewrite hashtable for mr and pin memory
