### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by chizhang118** [bd-iaas-us/infiniStore#31]
- [ ] #50
- [ ] #51 
- [ ] **find a good ratio of PD seperation (re-read papers)**
- [ ] Hash-based prefix caching(cache_engine). higher cache rate than origin vllm
    - [ ] prefill kvcache 
    - [ ] decoding kvcache
- [ ] Overlap data transmission and previous layer calculation.
- [ ] use gossip protocol to talk to each other
- [x] tune RDMA performance on H800
- [x] migrate specific code from H800 to T4(T4 has very limited BAR1 memory, so we have to use local_gpu_copy insdead of RDMA)

**Comment by thesues** [comment]
move unfinished goal to next milestone
